FROM node:alpine
WORKDIR /app

# COPY the package.json file, update any deps and install them
COPY package.json .
RUN yarn

# copy the whole source folder(the dir is relative to the Dockerfile
COPY . .

CMD [ "yarn", "start" ]